proFour/appFour/urls.py
from django.urls import path
from . import views

app_name = 'appFour'

urlpatterns = [
    path('main/', views.main, name='main'),
    path('other/', views.other, name='other'),
]

proFour/proFour/urls.py
from django.contrib import admin
from django.urls import path, include
from appFour import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('appFour/', include('appFour.urls')),
]

proFour/appFour/models.py
from django.db import models

# Create your models here.

proFour/appFour/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'index.html', {'text': 'hello world', 'number': 100})


def other(request):
    return render(request, 'other.html')


def main(request):
    return render(request, 'main.html')

proFour/templates/base.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">admin</a></li>
          <li><a class="navbar-link" href="{% url 'appFour:other' %}">other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
        {% block body_block %}
        <!-- anything outside will be inherited  if you extend -->
        {% endblock %}
    </div>
</body>
</html>

proFour/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load my_extras %}

{% block body_block %}
    <h1>Welcome to the index page!</h1>
    {{ text|title }}
    <br>
    {{ number|addition:50 }}
{% endblock %}

proFour/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>main</title>
</head>
<body>
    <h1>Welcome to the main page!</h1>
    <a href="{% url 'appFour:other' %}">others</a>
    <br>
    <a href="{% url 'admin:index' %}">admin</a>
    <br>
    <a href="{% url 'index' %}">index</a>

</body>
</html>

proFour/templates/other.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block body_block %}
    <h1>Welcome to the others page!</h1>
{% endblock %}